# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qiheng/phd/obstacles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qiheng/phd/obstacles

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qiheng/phd/obstacles/CMakeFiles /home/qiheng/phd/obstacles/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qiheng/phd/obstacles/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 3d

# Build rule for target.
3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3d
.PHONY : 3d

# fast build rule for target.
3d/fast:
	$(MAKE) -f CMakeFiles/3d.dir/build.make CMakeFiles/3d.dir/build
.PHONY : 3d/fast

#=============================================================================
# Target rules for targets named create_regions

# Build rule for target.
create_regions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create_regions
.PHONY : create_regions

# fast build rule for target.
create_regions/fast:
	$(MAKE) -f CMakeFiles/create_regions.dir/build.make CMakeFiles/create_regions.dir/build
.PHONY : create_regions/fast

3dregions.o: 3dregions.cpp.o

.PHONY : 3dregions.o

# target to build an object file
3dregions.cpp.o:
	$(MAKE) -f CMakeFiles/3d.dir/build.make CMakeFiles/3d.dir/3dregions.cpp.o
.PHONY : 3dregions.cpp.o

3dregions.i: 3dregions.cpp.i

.PHONY : 3dregions.i

# target to preprocess a source file
3dregions.cpp.i:
	$(MAKE) -f CMakeFiles/3d.dir/build.make CMakeFiles/3d.dir/3dregions.cpp.i
.PHONY : 3dregions.cpp.i

3dregions.s: 3dregions.cpp.s

.PHONY : 3dregions.s

# target to generate assembly for a file
3dregions.cpp.s:
	$(MAKE) -f CMakeFiles/3d.dir/build.make CMakeFiles/3d.dir/3dregions.cpp.s
.PHONY : 3dregions.cpp.s

regions.o: regions.cpp.o

.PHONY : regions.o

# target to build an object file
regions.cpp.o:
	$(MAKE) -f CMakeFiles/create_regions.dir/build.make CMakeFiles/create_regions.dir/regions.cpp.o
.PHONY : regions.cpp.o

regions.i: regions.cpp.i

.PHONY : regions.i

# target to preprocess a source file
regions.cpp.i:
	$(MAKE) -f CMakeFiles/create_regions.dir/build.make CMakeFiles/create_regions.dir/regions.cpp.i
.PHONY : regions.cpp.i

regions.s: regions.cpp.s

.PHONY : regions.s

# target to generate assembly for a file
regions.cpp.s:
	$(MAKE) -f CMakeFiles/create_regions.dir/build.make CMakeFiles/create_regions.dir/regions.cpp.s
.PHONY : regions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 3d"
	@echo "... create_regions"
	@echo "... 3dregions.o"
	@echo "... 3dregions.i"
	@echo "... 3dregions.s"
	@echo "... regions.o"
	@echo "... regions.i"
	@echo "... regions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

